version: '3.9'

services:
  weatherbot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: python api.py

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
